sudo: false
language: php

php:
    - 7.0

before_script:
    - composer install

script:
    - ./vendor/bin/phpcs --colors --report-width=auto --warning-severity=0 --standard=PSR2 src
    - ./vendor/bin/phpunit