sudo: false
language: php

php:
    - 7.0
    - 5.6

before_script:
    - composer install

script:
    - ./vendor/bin/phpcs --colors --report-width=auto --warning-severity=0 --standard=PSR2 "src"
    - ./vendor/bin/propel model:build
    - ./vendor/bin/phpunit

after_script:
    - php vendor/bin/coveralls