sudo: false
language: php

php:
    - 7.0

before_script:
    - composer install

script:
    - ./vendor/bin/phpcs --config-set show_warnings 0
    - ./vendor/bin/phpcs --standard=PSR2 ./src
    - ./vendor/bin/phpunit